### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.downloader'

### ISSUE THREAD

**Issue by r3gor** [Devil64-Dev/automated-dtool#10]
parece en la último commit de la rama master no tiene algunos ficheros o están renombrados y me lanza este error al tratar ejecutar el programa:

```
# ./dtool.py
Traceback (most recent call last):
  File "./dtool.py", line 3, in <module>
    from utils.downloader.resources import ResourceDownloader
ModuleNotFoundError: No module named 'utils.downloader'
```

como lo podria solucionar? gracias de antemano

**Comment by estebanardila57** [comment]
Hola , acabo de recibir este mismo error . has podido encontrar algo al respecto ?
![image](https://user-images.githubusercontent.com/43124834/120898460-96566780-c5f0-11eb-8ca7-48f29b297afb.png)

**Comment by Domadrona** [comment]
Hola, igualmente tengo el mensaje

![image](https://user-images.githubusercontent.com/43122606/124051279-cd4a4e00-d9e1-11eb-8a4e-a5fc687bef11.png)

**Comment by Devil64-Dev** [comment]
Hola, desgraciadamente esta versión del programa ya no es funcional, actualmente me encuentro desarrollando un nuevo programa para el mismo propósito que abarca más sitios y con muchas más características. La mala noticia es que el nuevo programa solo estara disponible bajo un entorno 100% Linux... Puedes usar VMWare o VirtualBox para instalar una distribución de Linux y poder ejecutar el programa.
