### ISSUE TITLE
Error  de descarga

### ISSUE THREAD

**Issue by JeanCarlosDEV17** [Devil64-Dev/automated-dtool#6]
![image](https://user-images.githubusercontent.com/76703380/113378539-e557f600-933c-11eb-923f-29fab3e12f0b.png)
 estaba descargando una escuela iba de maravilla hasta que llego este curso, posterior lo intente de forma individual mismo resultado, estoy pensando que  esa comilla en el nombre  afecta al algoritmo

**Comment by JeanCarlosDEV17** [comment]
si era el caracter  "   '   " lo  arregle añadiendolo a la lista del diccionario

**Comment by Devil64-Dev** [comment]
Hola, gracias por notificarme sobre ese fallo, me disculpó ya que sinceramente no tuve mucho tiempo de probarlo. Agradecería si me pudieras notificar de otros posibles fallos que existen, pues no puedo probar el programa actualmente ya que no cuento con una suscripción activa.

Gracias.

**Comment by JeanCarlosDEV17** [comment]
no hay problema, y no hay que disculparse, no hay codigo perfecto, y menos en ese tiempo de desarrollo
