### ISSUE TITLE
Videos de youtube no se descargan

### ISSUE THREAD

**Issue by JeanCarlosDEV17** [Devil64-Dev/automated-dtool#7]
![image](https://user-images.githubusercontent.com/76703380/113548422-21958b80-95b5-11eb-97ef-15ff28e252c9.png)

despues de un rato intentando ver que pasaba con los videos de youtube, por que vi que te esforzaste con implementarlo pero no los bajaba, al analizar  el comando la url que generaba el programa al momento de ejecutarse y comparando directamente desde platzi al copiarla faltaba el ultimo caracter, ahora creo que esta linea lo afecta, me puedes explicar que funcion tiene o por que le restas 1  caracter
![image](https://user-images.githubusercontent.com/76703380/113548637-7f29d800-95b5-11eb-8c43-3b95291b9db7.png)

**Comment by Devil64-Dev** [comment]
Si, también me di cuenta cuando estaba probando las nuevas caracteristicas, es debido a que se cambió como se estructuraban las URLs.

**Comment by Devil64-Dev** [comment]
El error se genera en:
`helper.py 73`
 `youtube_url = "https://" + youtube_url[:len(youtube_url) - 1]`

Debes cambiar la línea anterior por esta:
`youtube_url = "https://" + youtube_url`
