### ISSUE TITLE
Problemas para instalar los módulos de python

### ISSUE THREAD

**Issue by estebanardila57** [Devil64-Dev/automated-dtool#9]
Que tal, soy yo de nuevo :( , tuve que formatear el sistema anterior , entonces me propuse a actualizar todo de nuevo , instale todo lo referido a ubuntu , instale WSL 2  en UBuntu 18.04 y ejecuté sudo apt-get update && sudo apt-get upgrade. para actualizar todas lo que estuviera  en una versión anterior,  instale python  y demas programas necesarios con el comando sudo apt-get install python3 youtube-dl ffmpeg , todo super bien hasta allí.

El problema sucede es cuando intento instalar los módulos de python con pip dentro de la carpeta del programa
![image](https://user-images.githubusercontent.com/43124834/120881794-3ed8dd00-c599-11eb-9e92-5cba55b4d8b9.png)

Es como si Pip no se ubiese instalado , entonces trato de ejecutar el otro comando sudo apt-get install wget

sh -c "$(wget -O- https://raw.githubusercontent.com/Devil64-Dev/automated-dtool/master/extra/install.sh)"

pero me sale el siguiente problema
![image](https://user-images.githubusercontent.com/43124834/120881830-7fd0f180-c599-11eb-99d9-bbcf83b0a0a4.png)

*Por favor discúlpame si eh omitido algo para poder que me reconozcan los comandos :( , también quería preguntarte sobre , si cambio la interfaz  y donde puedo encontrar el video demo mostrando el proceso de uso , mil disculpas por las molestias

**Comment by r3gor** [comment]
has intentado hacer primero ```sudo apt install python3-pip``` ?

**Comment by estebanardila57** [comment]
Si lo intente , pero es que aparecer estoy tenido problemas con mi terminal y paquetes rotos el problema es que e probado de todo pero aun no e logrado resolverlo , soy muy nuevo en linux pero e leído que se puede editar el sources.list pero no e  sabido como , pero bueno muchas gracias por responder 
![image](https://user-images.githubusercontent.com/43124834/120896896-360ff780-c5e9-11eb-83bf-d33ce44d9fd1.png)

**Comment by estebanardila57** [comment]
acabo de instalar correctamente el Pip , era un problema en mi archivo  sources.list  con unos paquetes que no eran compatibles muchas gracias
